FEDERATION_SERVER="https://api.stellar.org/federation"

[DOCUMENTATION] 
ORG_NAME="MULTIGRAM" 
ORG_URL="https://gram.toml.host" 
ORG_LOGO="https://gram.toml.host/logo.png" 

[[CURRENCIES]] 
code="GRAM" 
issuer="GAANUKUPS2TJ7L2AS2RNC7ZBM753XYFP2KOY65H3WSRCIFKERNANGRAM" 
status="LIVE"
name="MULTIGRAM" 
desc="Multigram brings real physical gold into Stellar Blockchain." 
display_decimals=7 
conditions="Every GRAM purchased will be back-up with every gram of real physical gold. The purity of gold is 99.99999% or equivalent with 24 Karat." 
image="https://gram.toml.host/logo.png" 
